name: compiler_unsupported
version: 1.19.0
description: >
  This is an unsupported copy of the dart2js source. The API of this package
  can and will change in unpredictable and incompatible ways.

author: Dart2js Team <compiler-dev@dartlang.org>
homepage: https://github.com/dart-lang/compiler_unsupported

environment:
  sdk: ">=1.11.0 <2.0.0"

dependencies:
  dart2js_info: ^0.2.0
  package_config: ^1.0.0
  pub_semver: ^1.2.1
  kernel: ^0.1.0
  # js:
  # js_ast:
  # js_runtime:
  # sdk_library_metadata:
  # dart2js_info:
  # lookup_map:

dev_dependencies:
  grinder: ^0.8.0
  path: any
  test: ^0.12.0
